---
abstract: 'A Periscope for Pandora'
author:
  - 'Delon Newman <delon.newman@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-PandoraPerisope
requires:
  Periscope: 0.0.3
version: 0.0.1
